name:               Pull Request

on:
  pull_request:
    branches:       [main]
    types:          [opened, synchronize]

jobs:
  # pull request-sepcific steps.
  validate_commits:
    name:           Conventional Commits
    runs-on:        ubuntu-latest

    steps:
      - name:       Checkout
        uses:       actions/checkout@v3
      # validate commits.
      - name:       Validate commits
        uses:       tomtom-international/commisery-action@master
        with:
          token:    ${{ secrets.GITHUB_TOKEN }}

  # lint code.
  lint:
    name:           Lint
    runs-on:        macos-latest

    steps:
      - name:       Checkout
        uses:       actions/checkout@v3
      # only lint on actual code changes.
      - uses:       dorny/paths-filter@v2
        id:         changes
        with:
          base:     ${{ github.base_ref }}
          filters:  |
            src:
              - '**/*.swift'
      - name:       Lint
        if:         steps.changes.outputs.src == 'true'
        run:        |
          set -o pipefail
          swiftlint lint --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'

  # build the library.
  build:
    name:           Build
    needs:          lint
    runs-on:        macos-latest

    steps:
      - name:       Checkout
        uses:       actions/checkout@v3
      # only build on actual code changes.
      - uses:       dorny/paths-filter@v2
        id:         changes
        with:
          base:     ${{ github.base_ref }}
          filters:  |
            src:
              - '**/*.swift'
      - name:       Build
        if:         steps.changes.outputs.src == 'true'
        run:        swift build
